export const CHANGE_CURRENT_MUSIC_INFO="CHANGE_CURRENT_MUSIC_INFO";
export const CHANGE_CURRENT_MUSIC_INDEX="CHANGE_CURRENT_MUSIC_INDEX";
export const CHANGE_BAR_PLAYLIST="CHANGE_BAR_PLAYLIST";
export const CHANGE_REPEAT_MODE="CHANGE_REPEAT_MODE";
export const CHANGE_CURRENT_LYRIC="CHANGE_CURRENT_LYRIC";
export const CHANGE_CURRENT_LRC_INDEX="CHANGE_CURRENT_LRC_INDEX";
export const CHANGE_CURRENT_URL="CHANGE_CURRENT_URL";

