export const CHANGE_CURRENT_MUSIC_INFO="CHANGE_CURRENT_MUSIC_INFO";
export const CHANGE_CURRENT_MUSIC_INDEX="CHANGE_CURRENT_MUSIC_INDEX";
export const CHANGE_BAR_PLAYLIST="CHANGE_BAR_PLAYLIST";
// export const CHANGE_MUSIC_URL="CHANGE_MUSIC_URL";