export const CHANGE_HIT_BANNERS = "CHANGE_HIT_BANNERS";
export const CHANGE_BIG_HITS = "CHANGE_BIG_HITS";
export const CHANGE_HIT_ALBUMS = "CHANGE_HIT_ALBUMS";
export const CHANGE_HIT_RANKINGS = "CHANGE_HIT_RANKINGS";

export const CHANGE_HIT_UPSURGE_RANKING = "CHANGE_HIT_UPSURGE_RANKING";
export const CHANGE_HIT_FRESH_RANKING = "CHANGE_HIT_FRESH_RANKING";
export const CHANGE_HIT_ORIGINAL_RANKING = "CHANGE_HIT_ORIGINAL_RANKING";
